host: 0.0.0.0
port: 8001
postgresql:
  host: db
  port: 5432
  db: muxwaf
  username: muxwaf
  password: muxwaf@password
  debug: true
log:
  writers: file,stdout
  logger_level: info
  logger_file: /tmp/muxwaf-apiserver.log
  log_rolling_policy: daily
  log_rotate_date: 1
  log_backup_count: 7