version: '3.1'

services:

  guard:
    image: xnile/muxwaf-guard:0.0.1
    restart: always
    ports:
      - 8083:8083
      - 8080:80
      - 8443:443

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh 

  apiserver:
    image: xnile/muxwaf-apiserver:0.0.1
    restart: always
    #volumes:
    #  - ./config.yaml:/etc/muxwaf/config.yaml
    depends_on:
      - db

  ui:
    image: xnile/muxwaf-ui:0.0.1
    restart: always
    ports:
      - 8000:80

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8088:8080
