{
 "title": "muxwaf",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(muxwaf_lua_memstats_alloc_bytes, instance) "
    }
   },
   {
    "name": "host",
    "label": "域名",
    "query": {
     "query": "label_values(muxwaf_requests, host) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总拦截",
   "type": "stat",
   "description": "拦截总次数",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(muxwaf_attacks_blocked{instance=~\"$node\", host=~\"$host\"}[${__range_s}s])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CC防护",
   "type": "stat",
   "description": "频率限制拦截次数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(muxwaf_attacks_blocked{rule_type=\"ratelimit\",instance=~\"$node\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP黑名单",
   "type": "stat",
   "description": "IP黑名单拦截次数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(muxwaf_attacks_blocked{rule_type=\"blacklist_ip\", instance=~\"$node\"}[${__range_s}s])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "地域级IP黑名单",
   "type": "stat",
   "description": "地域级IP黑名单拦截次数",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(muxwaf_attacks_blocked{rule_type=\"blacklist_region\", instance=~\"$node\"}[${__range_s}s])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(muxwaf_requests{instance=~\"$node\", host=~\"$host\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (muxwaf_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(muxwaf_request_bytes_total{instance=~\"$node\", host=~\"$host\"}[5m]))",
     "legendFormat": "流入"
    },
    {
     "expr": "sum(rate(muxwaf_response_bytes_total{instance=~\"$node\", host=~\"$host\"}[5m]))",
     "legendFormat": "流出"
    }
   ]
  },
  {
   "title": "Lu内存使用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(instance) (muxwaf_lua_memstats_alloc_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Lua内存使用（每worker）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "muxwaf_lua_memstats_alloc_bytes",
     "legendFormat": "{{instance}},worker{{worker_id}}"
    }
   ]
  },
  {
   "title": "shm-based内存使用",
   "type": "timeseries",
   "description": "shm-based dictionary information",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "muxwaf_shm_free_bytes{instance=~\"$node\"}",
     "legendFormat": "{{name}}[{{node}}]可用内存"
    },
    {
     "expr": "muxwaf_shm_total_bytes{instance=~\"$node\"}",
     "legendFormat": "{{name}}[{{node}}]总内存"
    }
   ]
  },
  {
   "title": "状态码",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(muxwaf_requests{instance=~\"$node\", host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "响应码占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(muxwaf_requests{instance=~\"$node\", host=~\"$host\", status!=\"204\"}[${__range_s}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "源站响应码占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(upstream_status) (increase(muxwaf_requests{instance=~\"$node\", host=~\"$host\", upstream_status!=\"-\", upstream_status!=\"204\"}[${__range_s}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "timeseries",
   "description": "RT",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(muxwaf_request_duration_second_bucket{instance=~\"$node\", host=~\"$host\"}[5m])) by (le, host))",
     "legendFormat": "p99 {{host}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(muxwaf_request_duration_second_bucket{instance=~\"$node\", host=~\"$host\"}[5m])) by (le, host))",
     "legendFormat": "p95 {{host}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(muxwaf_request_duration_second_bucket{instance=~\"$node\", host=~\"$host\"}[5m])) by (le, host))",
     "legendFormat": "p90 {{host}}"
    }
   ]
  }
 ]
}